/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Modelos;

import BaseDeDatos.ConexionMySQL;
import Reportes.GenerarReportes;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author usuario
 */
public class ConsultaPlanes extends javax.swing.JFrame {

    /**
     * Creates new form ConsultaPlanes
     */
    DefaultTableModel modelo;
    public ConsultaPlanes() {
        initComponents();
        
        CargarTablaPlanes("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        Imprimir = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtBuscarPlan = new javax.swing.JTextField();
        btnBuscarPlan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblConsultaPlanes = new javax.swing.JTable();
        btnSalirConsulta = new javax.swing.JButton();

        jPopupMenu1.setComponentPopupMenu(jPopupMenu1);
        jPopupMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Imprimir.setText("Ver Comprobante");
        Imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImprimirActionPerformed(evt);
            }
        });
        jPopupMenu1.add(Imprimir);

        jPopupMenu1.getAccessibleContext().setAccessibleName("");
        jPopupMenu1.getAccessibleContext().setAccessibleParent(jPopupMenu1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Consulta Planes Fijos");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Consulta Planes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel1.setText("Buscar Plan: ");

        txtBuscarPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarPlanActionPerformed(evt);
            }
        });

        btnBuscarPlan.setText("Buscar");
        btnBuscarPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPlanActionPerformed(evt);
            }
        });

        tblConsultaPlanes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblConsultaPlanes.setComponentPopupMenu(jPopupMenu1);
        jScrollPane1.setViewportView(tblConsultaPlanes);

        btnSalirConsulta.setText("Salir");
        btnSalirConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirConsultaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtBuscarPlan, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscarPlan, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(111, 111, 111)
                        .addComponent(btnSalirConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSalirConsulta, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtBuscarPlan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscarPlan)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1)
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.getAccessibleContext().setAccessibleName("ConsultaPlanes");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarPlanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarPlanActionPerformed

    private void btnBuscarPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPlanActionPerformed
        String valor="";
        valor= txtBuscarPlan.getText();
        
        CargarTablaPlanes(valor);
        
    }//GEN-LAST:event_btnBuscarPlanActionPerformed

    private void btnSalirConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirConsultaActionPerformed
       ConsultaPlanes.this.dispose();
    }//GEN-LAST:event_btnSalirConsultaActionPerformed

    private void ImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImprimirActionPerformed
        int filasel;
        int idplanfijo=0;
        String idString="";
        GenerarReportes repFijo= new GenerarReportes(); 
        modelo= (DefaultTableModel) tblConsultaPlanes.getModel();
        try
           {
               System.out.println("entra1");
               filasel=tblConsultaPlanes.getSelectedRow();
               System.out.println("entra2");
               if (filasel==-1)
               {
                   System.out.println("entra3");
                   JOptionPane.showMessageDialog(null, "No se ha seleccionado ninguna fila");
               }
               else
               {
                   //accion="Modificar";
                   System.out.println("entra4");
                   idString= (String)modelo.getValueAt(filasel, 0);
                   System.out.println(idString);
                  
                   //habilitar();
                   idplanfijo= Integer.valueOf(idString);
                   System.out.println(idplanfijo);
                   repFijo.reportePlanFijo(idplanfijo);
               }     
           }
        catch (HeadlessException | NumberFormatException e)
                {
                    
                }
    }//GEN-LAST:event_ImprimirActionPerformed
    
    //carga tabla Articulos
    void CargarTablaPlanes(String valor){
        String sSQL="";
       
        ///configuramos la tabla.
        String [] titulos= {"Nro de Plan","Tipo","Proveedor","Importe","Fecha","IVA","Sector","MotivoSNC","Descuento","Desc.Descuento", "Comprador" };
        String [] registro= new String[11];
        modelo = new DefaultTableModel(null,titulos);
        ///realizamos la conexion con la bdd.
        ConexionMySQL mysql= new ConexionMySQL();
        Connection cn= mysql.Conectar();
        
       ///ingresamos la consulta
        sSQL="select pl.idPlan_descuento as Plan_Nro, pl.tipo_plan as Tipo,pr.razon_social as Proveedor, "+
             "pl.fechaActual as Fecha, pl.importe as Importe, ti.descripcion_iva as IVA, "+ 
             "sec.descripcion as Sector, mot.descripcion as MotivoSNC, pl.descuento as Descuento, "+
             "pl.descuento_descripcion, pl.obs_proveedor, pl.obs_comprador, "+
             "concat (usr.apellido, ' ' , usr.nombre) as Comprador "+
             "from plan_descuento as pl "+ 
             "INNER JOIN proveedor as pr ON pr.idproveedor = pl.Proveedor_idProveedor "+
             "INNER JOIN sector as sec ON sec.idSector= pl.Sector_idSector "+
             "INNER JOIN motivo_snc as mot ON mot.idMotivo_SNC= pl.Motivo_SNC_idMotivo_SNC "+
             "INNER JOIN usuario as usr ON usr.idUsuario= pl.Usuario_idUsuario "+
             "INNER JOIN tipo_iva as ti ON ti.idTipo_IVA= pl.tipo_IVA_idtipo_IVA "+
             "WHERE "+ 
             "CONCAT(pl.idPlan_descuento, ' ',pl.tipo_plan, ' ', importe, ' ', pr.razon_social, ' ', pl.fechaActual, ' ', "+
             "sec.descripcion, ' ',mot.descripcion, ' ', pl.descuento,' ' ,ti.descripcion_iva, ' ', "+
             "concat (usr.apellido, ' ' , usr.nombre)) "+ 
             "LIKE '%"+ valor +"%' order by Plan_Nro" ; 
        
        try 
        {
            Statement st= cn.createStatement();
            ResultSet rs= st.executeQuery(sSQL);
            
            while (rs.next())
            {
                registro[0]=rs.getString("Plan_Nro");
                registro[1]=rs.getString("Tipo");
                registro[2]=rs.getString("Proveedor");
                registro[3]=rs.getString("Importe");
                registro[4]=rs.getString("Fecha");
                registro[5]=rs.getString("IVA");
                registro[6]=rs.getString("Sector");
                registro[7]=rs.getString("MotivoSNC");
                registro[8]=rs.getString("Descuento");
                registro[9]=rs.getString("pl.descuento_descripcion");
                //registro[10]=rs.getString("pl.obs_comprador");
                //registro[11]=rs.getString("pl.obs_proveedor");
                registro[10]=rs.getString("Comprador");
                modelo.addRow(registro);
              }
            tblConsultaPlanes.setModel(modelo);
                        
        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        
  }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
         ConexionMySQL mysql= new ConexionMySQL();
         Connection cn= mysql.Conectar();
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaPlanes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaPlanes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaPlanes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaPlanes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ConsultaPlanes().setVisible(true);
         });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Imprimir;
    private javax.swing.JButton btnBuscarPlan;
    private javax.swing.JButton btnSalirConsulta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblConsultaPlanes;
    private javax.swing.JTextField txtBuscarPlan;
    // End of variables declaration//GEN-END:variables
}
